version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16.13
    steps:
      - checkout
      - run:
          name: update npm
          command: npm install -g npm@latest
      - run:
          name: install npm
          command: npm install
      - run:
          name: run updateData script
          command: node utils/updateData.js

workflows:
  version: 2
  build:
    jobs:
      - build