version: 2.1

# Set the job to not run by default
parameters:
  run:
    type: boolean
    default: false

# Definition of the build job
jobs:
  build:
    docker:
      - image: cimg/node:20.5.1
    environment:
      VERCEL_ORG_ID: $VERCEL_ORG_ID
      VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID
      VERCEL_TOKEN: $VERCEL_TOKEN
    steps:
      - checkout
      - run:
          name: Install npm to the latest version
          command: sudo npm install -g npm@latest
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install vercel globally
          command: sudo npm install -g vercel
      - run:
          name: Update movie data
          command: node data/updateData.js movie update_ids update_db
      - run:
          name: Update tvshow data
          command: node data/updateData.js tvshow update_ids update_db
      - run:
          name: Run tests
          command: npm run test_remote

# Run the build job
workflows:
  build:
    when: << pipeline.parameters.run >>
    jobs:
      - build
