version: 2.1

# Set the job to not run by default
parameters:
  run:
    type: boolean
    default: false

# Definition of the build job
jobs:
  build:
    docker:
      - image: circleci/node:16.13
    steps:
      - checkout
      - run:
          name: update npm to the latest version
          command: sudo npm install -g npm@latest
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: run updateData movie script
          command: node data/updateData.js movie update_ids update_db
      - run:
          name: run updateData tvshow script
          command: node data/updateData.js tvshow update_ids update_db
      - run:
          name: run test
          command: npm run test_remote

# Run the build job
workflows:
  build:
    when: << pipeline.parameters.run >>
    jobs:
      - build
