version: 2.1

parameters:
  run:
    type: boolean
    default: false
  all:
    type: boolean
    default: false
  all_second:
    type: boolean
    default: false

commands:
  setup_env:
    steps:
      - checkout
      - run:
          name: Install npm to the latest version
          command: sudo npm install -g npm@latest
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install vercel globally
          command: sudo npm install -g vercel
  run_tests:
    steps:
      - run:
          name: Run tests
          command: npm run test_remote
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/
            JEST_JUNIT_ADD_FILE_ATTRIBUTE: "true"
      - store_test_results:
          path: ./reports/

jobs:
  build:
    docker:
      - image: cimg/node:20.5.1
    steps:
      - setup_env
      - run:
          name: Update movie data
          command: node data/updateData.js movie update_ids update_db
      - run_tests
      - run:
          name: Update tvshow data
          command: node data/updateData.js tvshow update_ids update_db
      - run_tests
  build_all:
    docker:
      - image: cimg/node:20.5.1
    parallelism: 30
    steps:
      - setup_env
      - run:
          name: Update all movie data first half
          command: npm run update-movie-data-first-half
      - run_tests
  build_all_second:
    docker:
      - image: cimg/node:20.5.1
    parallelism: 30
    steps:
      - setup_env
      - run:
          name: Update all movie data second half
          command: npm run update-movie-data-second-half
      - run_tests
      - run:
          name: Update all tvshow data all
          command: npm run update-tvshow-data-all
      - run_tests

workflows:
  build:
    when: << pipeline.parameters.run >>
    jobs:
      - build
  build_all:
    when: << pipeline.parameters.all >>
    jobs:
      - build_all
  build_all_second:
    when: << pipeline.parameters.all_second >>
    jobs:
      - build_all_second
