version: 2.1

parameters:
  run:
    type: boolean
    default: false
  all:
    type: boolean
    default: false

commands:
  setup_env:
    steps:
      - checkout
      - run:
          name: Install npm to the latest version
          command: sudo npm install -g npm@latest
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install vercel globally
          command: sudo npm install -g vercel

jobs:
  build:
    docker:
      - image: cimg/node:20.5.1
    steps:
      - setup_env
      - run:
          name: Update movie data
          command: node data/updateData.js movie update_ids update_db
      - run:
          name: Update tvshow data
          command: node data/updateData.js tvshow update_ids update_db
      - run:
          name: Run tests
          command: npm run test_remote
  build_all:
    docker:
      - image: cimg/node:20.5.1
    steps:
      - setup_env
      - run:
          name: Update all movie data
          command: node -e "let d = new Date(); let day = d.getDate(); console.log((day - 1) * 1500);" | xargs -I {} node data/updateData.js movie no_update_ids update_db no_local no_active no_check {} no_skip force
      - run:
          name: Update all tvshow data
          command: node -e "let d = new Date(); let day = d.getDate(); if (day >= 25) {day = day - 24}; console.log((day - 1) * 1500);" | xargs -I {} node data/updateData.js tvshow no_update_ids update_db no_local no_active no_check {} no_skip force

workflows:
  build:
    when: << pipeline.parameters.run >>
    jobs:
      - build
  build_all:
    when: << pipeline.parameters.all >>
    jobs:
      - build_all
