version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16.13
    steps:
      - checkout
      - run:
          name: update npm
          command: sudo npm install -g npm@latest
      - run:
          name: install npm
          command: npm install
      - run:
          name: run updateData script for movies
          command: node utils/updateData.js circleci movie active update_ids update_db
      - run:
          name: run updateData script for tvshows
          command: node utils/updateData.js circleci tvshow active update_ids update_db

workflows:
  version: 2
  build:
    jobs:
      - build
